### ISSUE TITLE
[Vanilla] The anvil GUI does not close once an anvil is destroyed.

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.16.x#62]
Describe the bug
A clear and concise description of what the bug is:

When you used by an Anvil and it get destroyed the gui does not disappear and you can carry on doing what ever in the anvil.

To Reproduce
Steps to reproduce the behaviour:

Get an damage anvil and use it. until it destroyed

Expected behaviour
A clear and concise description of what you expected to happen:

for the gui disappear once the anvil is destroyed.  

Screenshots
If applicable, add screenshots to help explain your problem:

https://youtu.be/kjdUv8iBb9M

Console Logs:

None

Info (please complete the following information):

Mod Name: no mods
Mod Version: no mods
Client forge version: 1.16.3 forge 34.1.42
Magma Version: magma-1.16.4-35.0.1-4ab2770
OS: Ubuntu 20

Additional context
Add any other context about the problem here:

**Comment by kwright02** [comment]
Fixed in my pr

**Comment by jahangir6969** [comment]
Can confirm still an issue with magma forge-1.16.5-36.1.0-c6d0ef4-CUSTOM

**Comment by kwright02** [comment]
Fixed, again
